In [29]:
from gradient_boosting import GradientBoostingClassifier 
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [30]:
df = pd.read_csv('Hotel Reservations.csv')
df

Booking_ID  no_of_adults  no_of_children  no_of_weekend_nights  \
0       INN00001             2               0                     1   
1       INN00002             2               0                     2   
2       INN00003             1               0                     2   
3       INN00004             2               0                     0   
4       INN00005             2               0                     1   
...          ...           ...             ...                   ...   
36270   INN36271             3               0                     2   
36271   INN36272             2               0                     1   
36272   INN36273             2               0                     2   
36273   INN36274             2               0                     0   
36274   INN36275             2               0                     1   

       no_of_week_nights type_of_meal_plan  required_car_parking_space  \
0                      2       Meal Plan 1                           0   
1                      3      Not Selected                           0   
2                      1       Meal Plan 1                           0   
3                      2       Meal Plan 1                           0   
4                      1      Not Selected                           0   
...                  ...               ...                         ...   
36270                  6       Meal Plan 1                           0   
36271                  3       Meal Plan 1                           0   
36272                  6       Meal Plan 1                           0   
36273                  3      Not Selected                           0   
36274                  2       Meal Plan 1                           0   

      room_type_reserved  lead_time  arrival_year  arrival_month  \
0            Room_Type 1        224          2017             10   
1            Room_Type 1          5          2018             11   
2            Room_Type 1          1          2018              2   
3            Room_Type 1        211          2018              5   
4            Room_Type 1         48          2018              4   
...                  ...        ...           ...            ...   
36270        Room_Type 4         85          2018              8   
36271        Room_Type 1        228          2018             10   
36272        Room_Type 1        148          2018              7   
36273        Room_Type 1         63          2018              4   
36274        Room_Type 1        207          2018             12   

       arrival_date market_segment_type  repeated_guest  \
0                 2             Offline               0   
1                 6              Online               0   
2                28              Online               0   
3                20              Online               0   
4                11              Online               0   
...             ...                 ...             ...   
36270             3              Online               0   
36271            17              Online               0   
36272             1              Online               0   
36273            21              Online               0   
36274            30             Offline               0   

       no_of_previous_cancellations  no_of_previous_bookings_not_canceled  \
0                                 0                                     0   
1                                 0                                     0   
2                                 0                                     0   
3                                 0                                     0   
4                                 0                                     0   
...                             ...                                   ...   
36270                             0                                     0   
36271                             0                                     0   
36272                            

In [31]:
# one hot encode columns type_of_meal_plan, room_type_reserved, market_segment_type and remove column Booking_ID
df = pd.get_dummies(df, columns=['type_of_meal_plan', 'room_type_reserved', 'market_segment_type'])
df = df.drop('Booking_ID', axis=1)
df

no_of_adults  no_of_children  no_of_weekend_nights  no_of_week_nights  \
0                 2               0                     1                  2   
1                 2               0                     2                  3   
2                 1               0                     2                  1   
3                 2               0                     0                  2   
4                 2               0                     1                  1   
...             ...             ...                   ...                ...   
36270             3               0                     2                  6   
36271             2               0                     1                  3   
36272             2               0                     2                  6   
36273             2               0                     0                  3   
36274             2               0                     1                  2   

       required_car_parking_space  lead_time  arrival_year  arrival_month  \
0                               0        224          2017             10   
1                               0          5          2018             11   
2                               0          1          2018              2   
3                               0        211          2018              5   
4                               0         48          2018              4   
...                           ...        ...           ...            ...   
36270                           0         85          2018              8   
36271                           0        228          2018             10   
36272                           0        148          2018              7   
36273                           0         63          2018              4   
36274                           0        207          2018             12   

       arrival_date  repeated_guest  ...  room_type_reserved_Room_Type 3  \
0                 2               0  ...                               0   
1                 6               0  ...                               0   
2                28               0  ...                               0   
3                20               0  ...                               0   
4                11               0  ...                               0   
...             ...             ...  ...                             ...   
36270             3               0  ...                               0   
36271            17               0  ...                               0   
36272             1               0  ...                               0   
36273            21               0  ...                               0   
36274            30               0  ...                               0   

       room_type_reserved_Room_Type 4  room_type_reserved_Room_Type 5  \
0                                   0                               0   
1                                   0                               0   
2                                   0                               0   
3                                   0                               0   
4                                   0                               0   
...                               ...                             ...   
36270                               1                               0   
36271                               0                               0   
36272                               0                               0   
36273                               0                               0   
36274                               0                               0   

       room_type_reserved_Room_Type 6 room_type_reserved_Room_Type 7  \
0                                   0                              0   
1                                   0                              0   
2                                   0                              0   
3                                   0      

In [32]:
df.head()

no_of_adults  no_of_children  no_of_weekend_nights  no_of_week_nights  \
0             2               0                     1                  2   
1             2               0                     2                  3   
2             1               0                     2                  1   
3             2               0                     0                  2   
4             2               0                     1                  1   

   required_car_parking_space  lead_time  arrival_year  arrival_month  \
0                           0        224          2017             10   
1                           0          5          2018             11   
2                           0          1          2018              2   
3                           0        211          2018              5   
4                           0         48          2018              4   

   arrival_date  repeated_guest  ...  room_type_reserved_Room_Type 3  \
0             2               0  ...                               0   
1             6               0  ...                               0   
2            28               0  ...                               0   
3            20               0  ...                               0   
4            11               0  ...                               0   

   room_type_reserved_Room_Type 4  room_type_reserved_Room_Type 5  \
0                               0                               0   
1                               0                               0   
2                               0                               0   
3                               0                               0   
4                               0                               0   

   room_type_reserved_Room_Type 6 room_type_reserved_Room_Type 7  \
0                               0                              0   
1                               0                              0   
2                               0                              0   
3                               0                              0   
4                               0                              0   

   market_segment_type_Aviation  market_segment_type_Complementary  \
0                             0                                  0   
1                             0                                  0   
2                             0                                  0   
3                             0                                  0   
4                             0                                  0   

   market_segment_type_Corporate  market_segment_type_Offline  \
0                              0                            1   
1                              0                            0   
2                              0                            0   
3                              0                            0   
4                              0                            0   

   market_segment_type_Online  
0                           0  
1                           1  
2                           1  
3                           1  
4                           1  

[5 rows x 31 columns]

In [33]:
# get labels and features
y = df['booking_status'].values
X = df.drop('booking_status', axis=1).values

In [34]:
# use standard scaler to scale the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
X


array([[ 0.29889263, -0.26147045,  0.2174012 , ..., -0.24264534,
         1.56383302, -1.33317382],
       [ 0.29889263, -0.26147045,  1.36599262, ..., -0.24264534,
        -0.63945446,  0.75008974],
       [-1.62897546, -0.26147045,  1.36599262, ..., -0.24264534,
        -0.63945446,  0.75008974],
       ...,
       [ 0.29889263, -0.26147045,  1.36599262, ..., -0.24264534,
        -0.63945446,  0.75008974],
       [ 0.29889263, -0.26147045, -0.93119021, ..., -0.24264534,
        -0.63945446,  0.75008974],
       [ 0.29889263, -0.26147045,  0.2174012 , ..., -0.24264534,
         1.56383302, -1.33317382]])

In [35]:
# encode the labels
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y


array([1, 1, 0, ..., 1, 0, 1])

In [36]:
# split the data into train, validate and test with 60%, 20% and 20% respectively
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
print(len(X_train) / len(X_test) * 100, '%')

400.0 %


In [38]:
# initialize the model
model = GradientBoostingClassifier(n_estimators=100)
# train the model
model.fit(X_train, y_train)

Training Gradient Boosting Classifier
Training tree 1
Training tree 2
Training tree 3
Training tree 4
Training tree 5
Training tree 6
Training tree 7
Training tree 8
Training tree 9
Training tree 10
Training tree 11
Training tree 12
Training tree 13
Training tree 14
Training tree 15
Training tree 16
Training tree 17
Training tree 18
Training tree 19
Training tree 20
Training tree 21
Training tree 22
Training tree 23
Training tree 24
Training tree 25
Training tree 26
Training tree 27
Training tree 28
Training tree 29
Training tree 30
Training tree 31
Training tree 32
Training tree 33
Training tree 34
Training tree 35
Training tree 36
Training tree 37
Training tree 38
Training tree 39
Training tree 40
Training tree 41
Training tree 42
Training tree 43
Training tree 44
Training tree 45
Training tree 46
Training tree 47
Training tree 48
Training tree 49
Training tree 50
Training tree 51
Training tree 52
Training tree 53
Training tree 54
Training tree 55
Training tree 56
Training tree 57
Tr

In [39]:
# test the model
y_pred = model.predict(X_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [40]:
# calculate the accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.3302549965541006

In [41]:
# calculate the precision, recall
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_pred, average='weighted')

(0.11028280189007701, 0.3302549965541006, 0.16534992677954766, None)

In [42]:
# save the model
import pickle
pickle.dump(model, open('model.pkl', 'wb'))

In [43]:
# load the model
model = pickle.load(open('model.pkl', 'rb'))

# End